version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus3_data:/prometheus
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana3_data:/var/lib/grafana:rw
    depends_on:
      - prometheus
    networks:
      - monitoring_network

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    environment:
      - NGINX_SERVER=nginx  # Set the NGINX server to the container name or IP
    restart: unless-stopped
    networks:
      - monitoring_network

  mktxp:
    restart: on-failure
    image: swoga/mikrotik-exporter
    volumes:
      - ./mktxp:/root/mktxp:rw
    ports:
      - "9436:9436"
    networks:
      - monitoring_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "192.168.88.232:9100:9100"
    networks:
      - monitoring_network
volumes:
  prometheus3_data:
  grafana3_data:

networks:
  monitoring_network:
    driver: bridge
