#Create a service.
kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  namespace: kube-system
  annotations:
    prometheus.io/port: '9100'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
  selector:
    app: node-exporter
  type: ClusterIP
---
#Set up kube-state-metrics.
kind: Service
apiVersion: v1
metadata:
  name: kube-state-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  ports:
    - name: http-metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: telemetry
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app.kubernetes.io/name: kube-state-metrics
  type: ClusterIP
---
#prov service
kind: Service
apiVersion: v1
metadata:
  name: prometheus-service
  namespace: matin
  annotations:
    prometheus.io/port: '9090'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus-server
  type: ClusterIP