apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: matin
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.grafana.spec.image }}
          imagePullPolicy: {{ .Values.grafana.spec.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.grafana.spec.ports.containerPort }}
              name: http-grafana
              protocol: {{ .Values.grafana.spec.ports.protocol }}
          livenessProbe:
            failureThreshold: {{ .Values.grafana.spec.livenessProb.failureThreshold }}
            initialDelaySeconds: {{ .Values.grafana.spec.livenessProb.initialDelaySeconds }}
            periodSeconds: {{ .Values.grafana.spec.livenessProb.periodSeconds }}
            successThreshold: {{ .Values.grafana.spec.livenessProb.successThreshold }}
            tcpSocket:
              port: {{ .Values.grafana.spec.livenessProb.tcpSocket.port }}
            timeoutSeconds: {{ .Values.grafana.spec.livenessProb.timeoutSeconds }}
          resources:
            requests:
              cpu: {{ .Values.grafana.spec.resources.requests.cpu }}
              memory: {{ .Values.grafana.spec.resources.requests.memory }}
            limits:
              memory: {{ .Values.grafana.spec.resources.limits.memory }}
              cpu: {{ .Values.grafana.spec.resources.limits.cpu }}

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: matin
spec:
  ports:
    - port: {{ .Values.Service.spec.ports.port }}
      protocol: {{ .Values.Service.spec.ports.protocol }}
      targetPort: {{ .Values.Service.spec.ports.targetPort }}
  selector:
    app: grafana
  sessionAffinity: {{ .Values.Service.spec.sessionAffinity }}
  type: {{ .Values.Service.spec.type }}
