name: Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # مرحله ساخت و تست Docker images
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and test Docker images
        run: |
          # راه‌اندازی سرویس‌ها با استفاده از Docker Compose
          docker-compose -f docker-compose.yml up -d
          
          # منتظر می‌مانیم تا سرویس‌ها شروع به کار کنند
          sleep 10  # مدت زمان مورد نیاز برای شروع سرویس‌ها

          # نمایش کانتینرهای در حال اجرا برای بررسی وضعیت
          docker ps

          # تست دسترسی به Prometheus
          echo "Testing Prometheus"
          curl -f http://localhost:9090/ || exit 1  # اگر به Prometheus دسترسی نبود، خطا می‌دهد

          # تست دسترسی به Grafana
          echo "Testing Grafana"
          curl -f http://localhost:3000/ || exit 1  # اگر به Grafana دسترسی نبود، خطا می‌دهد

          # تست دسترسی به Nginx Exporter
          echo "Testing Nginx Exporter"
          curl -f http://localhost:9113/ || exit 1  # اگر به Nginx Exporter دسترسی نبود، خطا می‌دهد

  # مرحله دپلوی به VPS
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.yml, prometheus.yml, prometheus.rule.yml"
          target: "~/monitoring"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/monitoring
            docker-compose down
            docker-compose up -d
